export const Types = {
    LOGIN_SUCCESSFULL : "LOGIN_SUCCESSFULL",
    UPDATE_SUCCESSFULL: "UPDATE_SUCCESSFULL",
    LOGOUT: "LOGOUT",
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_PRODUCTS: "GET_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    CLEAR_CART: "CLEAR_CART",
    GET_USER: "GET_USER",
    REFRESH_TOKEN: "REFRESH_TOKEN"
}